- name: Setting Hostname
  hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: Disable swap
  shell: swapoff -a

- name: Remove auto mount swap in /etc/fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: 'swap'

- name: Config k8s needed modules (overlay, br_netfilter)
  template:
    src: module-k8s.conf.j2
    dest: /etc/modules-load.d/k8s.conf
    mode: '0644'
    owner: root
    group: root

- name: Config k8s needed sysctl
  template:
    src: sysctl-k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf
    mode: '0644'
    owner: root
    group: root

- name: Reboot, apply swapoff, modules, and sysctl
  reboot:

- name: Install CRI-O
  include_tasks: "{{ role_path }}/tasks/tasks.d/install-crio.yml"

- name: Config kubernetes repo
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: '0644'
    owner: root
    group: root

- name: Install kubelet kubeadm kubectl
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    disable_excludes: kubernetes
