- name: Setting Hostname
  hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: Disable swap
  shell: swapoff -a

- name: Remove auto mount swap in /etc/fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: 'swap'

- name: Config k8s needed modules (overlay2, br_netfilter)
  template:
    src: module-k8s.conf.j2
    dest: /etc/modules-load.d/k8s.conf
    mode: '0644'
    owner: root
    group: root

- name: Config k8s needed sysctl
  template:
    src: sysctl-k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf
    mode: '0644'
    owner: root
    group: root

- name: Reboot, apply swapoff, modules, and sysctl
  reboot:

- name: Install CRI-O
  include_tasks: "{{ role_path }}/tasks/tasks.d/install-crio.yml"

- name: Install pre-require apt packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - python3-pip
      - nfs-common
    update_cache: true
      
- name: Install pre-require python packages
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes 
      - jsonpatch

- name: Create keyrings folder
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Kubernetes GPG key
  apt_key:
    id: DE15B14486CD377B9E876E1A234654DA9A296436
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes apt repo
  lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    create: yes
    mode: '0644'

- name: Install kubelet kubeadm kubectl
  apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: true

- name: Reboot all nodes and master
  reboot:

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: true
