- name: Add CRI-O key
  become: true
  shell: curl -fsSL {{ CRIO_REPO_URL }}Release.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/cri-o-apt-keyring.gpg

- name: Config CRI-O repo
  become: true
  lineinfile:
    path: '/etc/apt/sources.list.d/cri-o.list'
    line: 'deb [signed-by=/etc/apt/trusted.gpg.d/cri-o-apt-keyring.gpg] {{ CRIO_REPO_URL }} /'
    create: yes
    mode: '0644'


- name: Install CRI-O via apt
  become: true
  apt:
    pkg: 
      - cri-o
    update_cache: yes

- name: Enable CRI-O systemd service
  systemd:
    name: crio
    state: started
    enabled: yes
